apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ec6bh1cin-python
  janus-idp.io/tekton: ec6bh1cin-python
  backstage.io/kubernetes-id: ec6bh1cin-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ec6bh1cin-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
